//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : StaticDate.cpp
//  @ Date : 2017/9/29
//  @ Author : 
//
//


#include "StaticDate.h"

StaticDate StaticDate::sharedStaticData(int ) {

}

void StaticDate::purge(int ) {

}

int StaticDate::intValueForKey(std::string key) {

}

char StaticDate::stringValueFrom(std::string Key) {

}

float StaticDate::floatValueFrimKey(int Key) {

}

bool StaticDate::booleanFromKey(std::string Key) {

}

cocos2s::CCPoint StaticDate::poinFromKey(std::string Key) {

}

cocos2d::CCRect StaticDate::rectValueFrimKey(std::string Key) {

}

cocos2d::CCSize StaticDate::sizeFromKey(int Key) {

}

bool StaticDate::init(int ) {

}

StaticDate::~StaticDate() {

}

StaticDate::StaticData() {

}

